import type { Metadata } from 'next';
import { Geist, Geist_Mono, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Aurora from '../components/Aurora';
import NavigationBar from '../components/navigation-bar';
import { SidebarProvider } from '@/components/ui/sidebar';
import AppSideBar from '@/components/app-sidebar';

const jetbrainsMono = JetBrains_Mono({
	subsets: ['latin'],
	variable: '--font-mono',
});

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
				'antialiased',
				geistSans.variable,
				geistMono.variable,
				'font-mono',
				jetbrainsMono.variable,
			)}>
			<body className="min-h-full flex flex-col bg-black">
				<SidebarProvider
					defaultOpen={false}
					className="w-full min-h-full">
					<AppSideBar />
				<div className="absolute top-0 z-[-1] inset-0">
					<Aurora
						colorStops={['#A855F7', '#bd97cf', '#ff27fb']}
						blend={0.05}
						amplitude={1.0}
						speed={0.5}
					/>
				</div>
				<main className="w-full min-h-full flex flex-col justify-start items-center">
					<NavigationBar />
					{children}
				</main>
				</SidebarProvider>
			</body>
		</html>
	);
}
